## Loading packages
```{r}
# roxygen2::roxygenize("BayesMultiMode") #not sure if needed

######## Run this line when adding new functions to the package + adding the function name into NAMESPACE
# devtools::document("BayesMultiMode") #create rd files to export functions
#### Run this line to install the package after every modification
# devtools::install("BayesMultiMode")
# devtools::run_examples("BayesMultiMode")
# devtools::build_manual("BayesMultiMode")
# devtools::build("BayesMultiMode")
# devtools::check("BayesMultiMode")
# devtools::check_rhub("BayesMultiMode")
# rcmdcheck::rcmdcheck("BayesMultiMode")
# Default data analysis using BayesMultimode
library(BayesMultiMode)
# devtools::install_github("jumpingrivers/inteRgrate")
# inteRgrate::check_pkg("BayesMultiMode")
```

## 
```{r}
roxygen2::roxygenize()
devtools::document()

devtools::test()

devtools::install()

devtools::check()
```

#### Loading all functions for testing before installing
```{r, eval = FALSE}
devtools::load_all()
```

#### Testing / https://r-pkgs.org/testing-design.html
```{r}
library(usethis)
# use_r("MEM")    # creates and opens R/fixed_point.R
use_test("new_BayesMixture") # creates and opens tests/testthat/test-fixed_point.R
```

```{r}
# 
# test_that("some long-running thing works", {
#   skip_on_cran()
#   # test code that can potentially take "a while" to run  
# })
# 
# # test second element of output
# 
# # if the test use mcmc estimation result we could do this :
# test_that("foofy() does this", {
#   useful_thing1 <- readRDS(test_path("fixtures", "useful_thing1.rds"))
#   expect_equal(foofy(useful_thing1, x = "this"), EXPECTED_FOOFY_OUTPUT)
# })
# 
# test_that("foofy() does that", {
#   useful_thing2 <- readRDS(test_path("fixtures", "useful_thing2.rds"))
#   expect_equal(foofy(useful_thing2, x = "that"), EXPECTED_FOOFY_OUTPUT)
# })

# # Objects or functions defined in a helper file are available to all of your tests. such as :
# new_useful_thing <- function() {
#   # your fiddly code to create a useful_thing goes here like create a dataset ?
# }
```

### DNA data
```{r, eval=TRUE}
# install.packages("readxl")
library(readxl)
library(gdata)

file = "d4z4_4_411obs_a1_c2_y3.xls"# data with 4 mode acc. to AIC BIC
mydata = read.xls(paste0("results.dnadata/data/", file))
df_d4z4 = tibble(value = mydata[,1],
                 type = "d4z4")

df_DNA = df_d4z4

ggplot(df_DNA, aes(x=value)) + 
  ggtitle("Data") +
  xlab("") + ylab("") +
  geom_histogram(binwidth=1,color="white")

d4z4 = df_d4z4$value
save(d4z4, file="data/d4z4.rda")
```

### data
```{r, eval=TRUE}
# source : https://people.maths.bris.ac.uk/~mapjg/mixdata (Richardson S, Green PJ (1997)

# galaxy
galaxy = c(9.172, 9.350,9.483,9.558,9.775,10.227,10.406,16.084,16.170,18.419,
           18.552,18.600,18.927,19.052,19.070,19.330,19.343,19.349,19.440,19.473,
           19.529,19.541,19.547,19.663,19.846,19.856,19.863,19.914,19.918,19.973,
           19.989,20.166,20.175,20.179,20.196,20.215,20.221,20.415,20.629,20.795,
           20.821,20.846,20.875,20.986,21.137,21.492,21.701,21.814,21.921,21.960,
           22.185,22.209,22.242,22.249,22.314,22.374,22.495,22.746,22.747,22.888,
           22.914,23.206,23.241,23.263,23.484,23.538,23.542,23.666,23.706,23.711,
           24.129,24.285,24.289,24.366,24.717,24.990,25.633,26.960,26.995,32.065,
           32.789,34.279)

save(galaxy, file="data/galaxy.rda")

# enzyme
enzyme = c(0.130,0.080,1.261,0.224,0.132,1.052,0.085,0.124,0.718,0.280,0.687,
           0.106,0.088,0.137,0.096,0.124,0.126,1.279,1.007,0.195,0.167,0.213,
           0.108,1.371,0.190,0.184,1.298,1.036,0.205,1.950,1.018,0.172,0.148,
           0.292,0.113,0.185,0.129,1.329,0.149,0.236,2.545,1.073,0.162,2.518,
           0.142,2.880,0.178,1.075,0.128,0.083,0.409,0.340,0.246,1.195,1.452,
           1.123,1.361,0.222,0.962,0.875,0.078,0.520,0.194,1.195,0.709,0.021,
           0.166,0.081,0.265,0.159,0.308,1.604,0.179,0.172,0.131,0.305,0.215,
           0.214,0.853,0.137,0.466,1.419,2.016,1.944,1.040,1.200,0.255,0.232,
           0.200,0.240,0.216,0.277,2.427,0.320,0.142,0.134,0.198,0.126,1.173,
           0.342,1.672,0.193,1.633,0.860,1.293,0.207,1.811,1.741,1.488,0.124,
           1.326,0.148,0.109,1.848,1.310,0.118,1.004,0.204,0.192,0.299,1.885,
           0.264,0.230,0.250,0.061,0.953,0.138,0.313,0.174,1.768,1.369,0.130,
           1.113,0.320,0.190,0.818,1.461,0.149,0.291,0.225,1.622,0.185,0.198,
           0.360,0.387,2.338,1.713,0.368,1.573,0.309,0.232,0.347,0.325,1.861,
           0.258,0.258,1.625,0.291,1.169,0.210,0.241,0.112,0.183,0.258,0.357,
           1.176,0.111,0.978,0.279,1.742,0.184,0.230,0.275,2.183,2.264,1.405,
           0.408,0.126,0.263,0.162,0.902,1.516,0.293,0.198,0.118,0.305,0.031,
           0.192,0.151,0.182,0.909,0.379,1.010,0.167,0.929,0.083,0.179,1.567,
           1.241,0.077,0.166,1.271,0.100,1.229,0.152,1.374,0.157,1.003,0.084,
           0.171,0.953,0.192,0.967,1.300,0.122,1.036,0.200,0.070,0.998,0.176,
           0.673,0.839,0.867,0.985,0.096,0.238,0.933,1.231,0.162,0.044,0.175,
           0.132,1.166,0.144,0.180,0.945,0.180,0.152,0.108,0.923,0.192,0.895,
           0.176,0.191,1.161)

save(enzyme, file="data/enzyme.rda")

# acidity
acidity = c(2.928524,3.910021,3.732896,3.688879,3.822098,3.735286,4.143135,
            4.276666,3.931826,4.077537,4.779123,4.234107,4.276666,4.543295,
            6.467388,4.127134,3.977811,4.264087,4.007333,3.921973,5.384495,
            4.912655,4.046554,4.043051,4.406719,4.505350,3.931826,6.752270,
            6.928538,5.994460,4.248495,4.060443,4.727388,6.047372,4.082609,
            4.244200,4.890349,4.416428,5.743003,4.127134,5.489764,4.778283,
            5.249652,4.855929,4.128746,4.442651,4.025352,4.290459,4.593098,
            4.652054,4.178992,4.382027,5.569489,5.049856,4.188138,6.629363,
            4.647271,4.784989,4.348987,5.361292,4.574711,4.442651,6.120297,
            4.060443,4.143135,4.510860,6.049733,4.510860,4.406719,6.343880,
            4.430817,5.929589,5.973301,4.481872,4.301359,6.452680,4.204693,
            4.143135,6.603944,4.644391,5.863631,4.025352,5.717028,5.308268,
            6.267201,4.060443,5.017280,4.510860,5.834811,4.330733,4.007333,
            6.806829,5.257495,4.624973,4.781641,4.099332,7.044382,3.914021,
            4.330733,4.016383,5.572154,4.043051,4.843399,4.110874,4.454347,
            4.356709,6.154858,6.284321,6.978214,4.301359,5.929855,4.465908,
            6.035481,6.726473,7.105130,6.014937,4.882802,7.032095,4.518522,
            6.476665,6.125558,4.189655,5.323498,4.938065,6.313548,5.853925,
            6.278146,7.020191,5.023881,4.262680,6.725634,6.489205,5.743003,
            6.739337,6.466145,6.855409,5.120983,5.913773,6.516932,4.058717,
            6.213608,6.554218,6.155707,4.314818,6.662494,6.749931,6.100319,
            4.112512,6.946014,4.131961,6.234411,6.595781,6.683861,6.957973,
            4.497585)
save(acidity, file="data/acidity.rda")
```