### ggplot theme
theme_gg <-  ggplot2::theme_bw()+ ggplot2::theme(strip.background=element_blank(),
                            strip.text=element_text(size=11),
                            title=element_text(size=11),
                            panel.border=element_blank(),
                            # panel.grid.major=element_blank(),
                            #panel.grid.minor=element_blank(),
                            #legend.key=element_rect(colour="white"),
                            legend.position="bottom",
                            legend.box.margin=margin(-10,0,-10,0),
                            legend.title=element_blank(),
                            legend.text=element_text(size=11),
                            axis.text=element_text(size=11),
                            axis.line.y = element_line(colour = 'grey', size=0.5, linetype="solid"),
                            axis.line.x = element_line(colour = 'grey', size=0.5, linetype="solid"),
                            plot.title=element_text(hjust=0.5, size=12, face="bold"))