# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("gaussian_mixture", "skew_normal_mixture", "skew_t_mixture", "student_mixture")

# load each stan module
Rcpp::loadModule("stan_fit4gaussian_mixture_mod", what = TRUE)
Rcpp::loadModule("stan_fit4skew_normal_mixture_mod", what = TRUE)
Rcpp::loadModule("stan_fit4skew_t_mixture_mod", what = TRUE)
Rcpp::loadModule("stan_fit4student_mixture_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
})
